package com.store.core.model;

public enum StoreType {

    SUPERMARKET,
    BAKERY,
    SHOES_STORE,
    GAS_STATION,
    PET_STORE,
    DRUG_STORE,
    RESTAURANT,
    BAR,
    HOTEL,
    STREAMING,
    ICE_CREAM_STORE,
    CLOTHES_STORE,
    BEER_STORE,
    MARKETPLACE,
    PIZZERIA,
    VETERINARY,
    DOCTOR,
    AIR_FLIGHT,
    SPORTS_STORE,
    BUTCHERY,
    UBER,
    RENTAL_CAR,
    CUT_HAIR,
    COURSES,
    GYM,
    CAR_MECHANIC_OFFICE
}
